name: mncapps
description: SDK to help you discover, and manage all MNC Apps to display it on your application
version: 2.4.0
homepage: "https://mobile.mncinnovation.id"
repository: https://github.com/mncinnovation/mnc-moreappsdk-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2
  package_info_plus: ^4.1.0
  device_apps: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
