name: mncapps
description: MNC Apps Flutter SDK
version: 0.2.0
author: handi.deyana@mncgroup.com
homepage: none
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  url_launcher: ^5.7.10
  webview_flutter: ^1.0.7
  package_info: ^0.4.3+4
  device_apps: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
